project:
  type: website
  output-dir: docs

website:
  title: "Jas Ahuja"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/index.html
        text: Blog

format:
  html:
    theme:
      light: cosmo
      dark: slate
    highlight-style:
      light: github
      dark: monokai
    code-line-numbers: true
    code-overflow: wrap
