project:
  type: website
  output-dir: docs

website:
  title: "Jasvinder Ahuja"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/
        text: Blog
